version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product
    volumes:
      - postgres-data:/var/lib/postgresql/data
  product-app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  postgres-data:
